#!/usr/bin/env python3
"""Generate a managed inspector and compare it with the actual JDK C ABI."""
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT=Path(__file__).resolve().parent.parent

def records():
    source=(ROOT/'src/JvmBridge/Native/Generated/Bindings.g.cs').read_text()
    result={}
    for match in re.finditer(r'public (?:unsafe )?partial struct (\w+)\s*\{',source):
        start=match.end(); end=start; depth=1
        while depth:
            if source[end]=='{': depth+=1
            elif source[end]=='}': depth-=1
            end+=1
        body=source[start:end-1]
        if body.strip(): result[match[1]]=body
    return result

def inspector(check=False):
    entries=[]
    for name,body in records().items():
        entries.append(f'        values["size.{name}"] = sizeof({name});')
        if name in ('JNINativeInterface_','JNIInvokeInterface_','jvmtiInterface_1_','jvmtiEventCallbacks','jvmtiHeapCallbacks'):
            for field in re.findall(r'public (?:delegate\*[^;\n]+>|nint|void\*) (\w+);',body):
                entries.append(f'        values["offset.{name}.{field}"] = Marshal.OffsetOf<{name}>(nameof({name}.{field})).ToInt64();')
    for name in ('can_tag_objects', 'can_retransform_classes', 'can_generate_all_class_hook_events'):
        entries += [f'        jvmtiCapabilities {name} = default;', f'        {name}.{name} = 1;', f'        values["capability.{name}"] = *(long*)&{name};']
    text='''// <auto-generated/>
using System.Runtime.InteropServices;
using System.Text.Json;
using JvmBridge.Native;
internal static unsafe class AbiInspector
{
    public static void Write()
    {
        Dictionary<string, long> values = new();
'''+ '\n'.join(entries)+'''
        Console.WriteLine(JsonSerializer.Serialize(values, AbiJsonContext.Default.DictionaryStringInt64));
    }
}
[System.Text.Json.Serialization.JsonSerializable(typeof(Dictionary<string, long>))]
internal partial class AbiJsonContext : System.Text.Json.Serialization.JsonSerializerContext;
'''
    path=ROOT/'tests/Fixtures/AbiInspector.g.cs'
    if check:
        if not path.exists() or path.read_text()!=text: raise RuntimeError('ABI inspector is stale.')
    else: path.write_text(text)

def probe_source(headers):
    jni=(headers/'jni.h').read_text()
    tooling=(headers/'jvmti.h').read_text()
    lines=['#include <stdio.h>','#include <stddef.h>','#include <string.h>','#include <jni.h>','#include <jvmti.h>','int main(void) {','printf("{\\\"pointer\\\":%llu", (unsigned long long)sizeof(void*));']
    for name in records():
        if name not in jni and name not in tooling: continue
        ctype='struct '+name if name in ('JNINativeInterface_','JNIInvokeInterface_','JNIEnv_','JavaVM_','jvmtiInterface_1_','_jvmtiEnv') else name
        lines.append(f'printf(",\\\"size.{name}\\\":%llu", (unsigned long long)sizeof({ctype}));')
    for name,header in [('JNINativeInterface_',jni),('JNIInvokeInterface_',jni),('jvmtiInterface_1_',tooling)]:
        match=re.search(r'(?:typedef )?struct '+name+r'\s*\{(.*?)\n\}',header,re.S)
        if not match: raise RuntimeError('Native table not found: '+name)
        fields=re.findall(r'\(JNICALL \*(\w+)\)|void\s*\*\s*(reserved\d+)\s*;',match[1])
        for left,right in fields:
            field=left or right
            if field.lower().startswith('reserved'): continue
            ctype='struct '+name
            lines.append(f'printf(",\\\"offset.{name}.{field}\\\":%llu", (unsigned long long)offsetof({ctype},{field}));')
    # Callback tables contain typedef-typed fields, so compare names against each header.
    for name in ('jvmtiEventCallbacks','jvmtiHeapCallbacks'):
        body=records()[name]
        for field in re.findall(r'public (?:delegate\*[^;\n]+>|nint|void\*) (\w+);',body):
            if re.search(r'\b'+field+r'\s*;',tooling):
                lines.append(f'printf(",\\\"offset.{name}.{field}\\\":%llu", (unsigned long long)offsetof({name},{field}));')
    for name in ('can_tag_objects', 'can_retransform_classes', 'can_generate_all_class_hook_events'):
        lines += [f'jvmtiCapabilities {name} = {{0}}; {name}.{name} = 1;', f'unsigned long long bits_{name} = 0; memcpy(&bits_{name}, &{name}, 8);', f'printf(",\\\"capability.{name}\\\":%llu", bits_{name});']
    lines += ['puts("}");' ,'return 0;','}']
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    inspector('--check' in sys.argv)
