#!/usr/bin/env python3
"""Generate the ABI declarations from pinned, unmodified OpenJDK headers."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / 'src/JvmBridge/Native/Generated/Bindings.g.cs'

def generate(check=False):
    provenance = json.loads((ROOT / 'eng/headers/provenance.json').read_text())
    for name, expected in provenance['headers'].items():
        actual = hashlib.sha256((ROOT / 'eng/headers' / name).read_bytes()).hexdigest()
        if actual != expected:
            raise RuntimeError(f'Header checksum mismatch: {name}')
    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / 'Bindings.cs'
        command = [os.environ['CLANGSHARP']] if 'CLANGSHARP' in os.environ else ['dotnet', 'tool', 'run', 'ClangSharpPInvokeGenerator', '--']
        command += ['-f', 'eng/headers/jni.h', 'eng/headers/jvmti.h', '-I', 'eng/shim', '-I', 'eng/headers', '-I', 'eng/headers/linux', '-x', 'c', '-a', '--target=aarch64-unknown-linux-gnu', '-n', 'JvmBridge.Native', '-o', str(output), '-c', 'codegen=latest', '-g', 'helper-types', 'file-scoped-namespaces', 'macro-bindings', '-e', 'Agent_OnLoad', 'Agent_OnAttach', 'Agent_OnUnload', 'JNI_OnLoad', 'JNI_OnUnload', 'JNI_CreateJavaVM', 'JNI_GetCreatedJavaVMs', 'JNI_GetDefaultJavaVMInitArgs', '-r', 'jlong=long', '-wcc', '*=Winapi']
        subprocess.run(command, cwd=ROOT, check=True)
        result = output.read_text(encoding='utf-8-sig')
        # va_list and C varargs have target-specific ABIs. Preserve their slots as
        # raw addresses, and use the typed, portable *A APIs from managed code.
        pattern = r'(\[NativeTypeName\("[^"\n]*(?:va_list|\.\.\.)[^"\n]*"\)\]\s*)public delegate\*[^;]+> (\w+);'
        result = re.sub(pattern, r'\1public nint \2;', result)
        result = '// <auto-generated/>\n#pragma warning disable CS8981 // Preserve native identifiers.\n// OpenJDK declarations: see NOTICE.md and eng/headers/provenance.json.\n' + result
        result = result.replace('\r\n', '\n')
        if check:
            if not OUTPUT.exists() or OUTPUT.read_text() != result:
                raise RuntimeError('Generated bindings are stale. Run python eng/generate.py.')
        else:
            OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            OUTPUT.write_text(result)
        print('Generated bindings verified.' if check else 'Generated bindings written.')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
