#!/usr/bin/env python3
"""Generate the coverage inventory and verify that no runnable matrix cell disappeared."""
import argparse
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent.parent

def report(verify=False,check=False):
    configuration=json.loads((ROOT/'eng/compatibility.json').read_text())
    entries=json.loads((ROOT/'eng/jdks.lock.json').read_text())['jdks']
    expected={(entry['rid'],entry['java'],entry['implementation']) for entry in entries if entry['status']=='available'}
    results=[]
    for path in (ROOT/'artifacts/results').glob('*/summary.json'):
        results.extend(json.loads(path.read_text())['results'])
    passed={(entry['rid'],entry['java'],entry['implementation']) for entry in results if entry['status']=='passed'}
    if verify:
        missing=expected-passed
        failed=[entry for entry in results if entry['status']=='failed']
        if missing or failed: raise RuntimeError(f'Incomplete compatibility run: {len(missing)} unverified cells, {len(failed)} failures. Missing: {sorted(missing)}')
        print(f'All {len(expected)} available JVM combinations passed real NativeAOT tests.')
        return
    text='# Compatibility inventory\n\nGenerated by `python eng/report.py` from pinned vendor inventories. Availability is not a claim that tests passed. See the matching commit’s CI reports for runtime verification.\n\n'
    text+='Each available Java/implementation/target combination is required by CI. Versions with no matching vendor archive are accounted for in the lock file.\n\n| Native target | HotSpot majors available | OpenJ9 majors available | Status / limitation |\n|---|---|---|---|\n'
    for target in configuration['targets']:
        versions=[]
        for implementation in configuration['implementations']:
            values=[str(entry['java']) for entry in entries if entry['rid']==target['rid'] and entry['implementation']==implementation and entry['status']=='available']
            versions.append(', '.join(values) or '—')
        state='Full agent + host + ABI tests required' if target['agent'] else ('Native build required; ' if target.get('build') else '')+target['status']+': '+target['reason']
        text+=f'| {target["rid"]} | {versions[0]} | {versions[1]} | {state} |\n'
    text+='\nJava majors: '+', '.join(map(str,configuration['javaMajors']))+'. One pinned GA build per available major/distribution/target; historical patch releases are not exhaustively tested. Android ART is not a Java SE version and needs its own platform suite. Browser/WASI and other non-NativeAOT targets cannot load this agent.\n'
    path=ROOT/'docs/compatibility.md';path.parent.mkdir(exist_ok=True)
    if check:
        if not path.exists() or path.read_text()!=text: raise RuntimeError('Compatibility documentation is stale.')
    else: path.write_text(text)
    print(f'{len(expected)} available combinations inventoried.')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--verify',action='store_true');parser.add_argument('--check',action='store_true');args=parser.parse_args();report(args.verify,args.check)
