using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace JvmBridge.Generator;

/// <summary>Generates opt-in native layout inspection from the consumer's referenced JvmBridge assembly.</summary>
[Generator]
public sealed class AbiInspectorGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<bool> enabled = context.AnalyzerConfigOptionsProvider.Select(
            static (options, cancellationToken) =>
            options.GlobalOptions.TryGetValue(key: "build_property.JvmBridgeAbiInspector", out string? value) && string.Equals(value, b: "true", StringComparison.OrdinalIgnoreCase)
        );

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(enabled),
            static (production, input) =>
        {
            if (!input.Right)
                return;

            INamedTypeSymbol? nativeValue = input.Left.GetTypeByMetadataName(fullyQualifiedMetadataName: "JvmBridge.Native.jvalue");

            if (nativeValue is null)
                return;

            production.AddSource(hintName: "AbiInspector.g.cs", SourceText.From(Generate(nativeValue.ContainingNamespace), Encoding.UTF8));
        }
        );
    }

    private static string Generate(INamespaceSymbol nativeNamespace)
    {
        List<string> lines = [
            """
            // <auto-generated/>
            internal static unsafe class AbiInspector
            {
                internal static void Write()
                {
                    using var stream = new global::System.IO.MemoryStream();
                    using (var writer = new global::System.Text.Json.Utf8JsonWriter(stream))
                    {
                        writer.WriteStartObject();

            """
        ];

        List<INamedTypeSymbol> types = [.. nativeNamespace.GetTypeMembers()];

        foreach (INamedTypeSymbol type in types.OrderBy(static type => type.Name, StringComparer.Ordinal))
        {
            List<IFieldSymbol> fields = [];

            foreach (ISymbol member in type.GetMembers())
            {
                if (member is IFieldSymbol { IsStatic: false } field)
                    fields.Add(field);
            }

            if (type.TypeKind != TypeKind.Struct || fields.Count == 0)
                continue;

            string typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            lines.Add($"            writer.WriteNumber(\"size.{type.Name}\", sizeof({typeName}));");

            bool isTable = type.Name is "JNINativeInterface_" or "JNIInvokeInterface_" or "jvmtiInterface_1_" or "jvmtiEventCallbacks" or "jvmtiHeapCallbacks";

            if (!isTable)
                continue;

            foreach (IFieldSymbol field in fields)
            {
                lines.Add(
                    $"            writer.WriteNumber(\"offset.{type.Name}.{field.Name}\", global::System.Runtime.InteropServices.Marshal.OffsetOf<{typeName}>(nameof({typeName}.@{field.Name})).ToInt64());"
                );
            }
        }

        foreach (string capability in new[] { "can_tag_objects", "can_retransform_classes", "can_generate_all_class_hook_events" })
        {
            lines.Add($"            global::JvmBridge.Native.jvmtiCapabilities {capability} = default;");
            lines.Add($"            {capability}.{capability} = 1;");
            lines.Add($"            writer.WriteNumber(\"capability.{capability}\", *(long*)&{capability});");
        }

        lines.Add(
            item: """
                        writer.WriteEndObject();
                    }
                    global::System.Console.WriteLine(global::System.Text.Encoding.UTF8.GetString(stream.ToArray()));
                }
            }
            """
        );

        return string.Join(separator: "\n", lines);
    }
}
