using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace JvmBridge.Generator;

[Generator]
public sealed class AgentGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidAgent = new("JVMB001", "Invalid JVM agent", "{0}", "JvmBridge", DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> agents = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is ClassDeclarationSyntax declaration && declaration.BaseList != null,
            static (syntax, cancellation) => syntax.SemanticModel.GetDeclaredSymbol(syntax.Node, cancellation) as INamedTypeSymbol)
            .Where(static type => type != null && !type.IsAbstract && DerivesAgent(type))
            .Select(static (type, _) => type ?? throw new InvalidOperationException("Missing agent symbol."));
        context.RegisterSourceOutput(agents.Collect().Combine(context.CompilationProvider).Combine(context.AnalyzerConfigOptionsProvider), static (production, input) =>
        {
            ImmutableArray<INamedTypeSymbol> types = input.Left.Left;
            bool configured = input.Right.GlobalOptions.TryGetValue("build_property.JvmBridgeAgent", out string? setting) && string.Equals(setting, "true", StringComparison.OrdinalIgnoreCase);
            if (types.Length == 0 && !configured)
                return;
            if (types.Length != 1)
            {
                production.ReportDiagnostic(Diagnostic.Create(InvalidAgent, Location.None, "Exactly one concrete JavaAgent subclass is required per native library."));
                return;
            }
            INamedTypeSymbol type = types[0];
            bool derivesAgent = DerivesAgent(type);
            bool accessible = true;
            for (INamedTypeSymbol? current = type; current != null; current = current.ContainingType)
                accessible &= current.DeclaredAccessibility != Accessibility.Private && current.Arity == 0;
            bool constructor = type.InstanceConstructors.Any(value => value.Parameters.Length == 0 && value.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal);
            if (!derivesAgent || type.IsAbstract || !accessible || !constructor)
            {
                production.ReportDiagnostic(Diagnostic.Create(InvalidAgent, type.Locations.FirstOrDefault(), "Agent must derive from JavaAgent, be non-generic and non-abstract, and have an accessible parameterless constructor."));
                return;
            }
            if (!input.Right.GlobalOptions.TryGetValue("build_property.JvmBridgeAgent", out string? enabled) || !string.Equals(enabled, "true", StringComparison.OrdinalIgnoreCase))
                production.ReportDiagnostic(Diagnostic.Create(InvalidAgent, type.Locations.FirstOrDefault(), "Set <JvmBridgeAgent>true</JvmBridgeAgent> in the agent project."));
            foreach (INamedTypeSymbol candidate in AllTypes(input.Left.Right.Assembly.GlobalNamespace))
                foreach (IMethodSymbol method in candidate.GetMembers().OfType<IMethodSymbol>())
                    foreach (AttributeData attribute in method.GetAttributes())
                        if (attribute.AttributeClass?.ToDisplayString() == "System.Runtime.InteropServices.UnmanagedCallersOnlyAttribute")
                            foreach (System.Collections.Generic.KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
                                if (argument.Key == "EntryPoint" && argument.Value.Value is string name && name is "Agent_OnLoad" or "Agent_OnAttach" or "Agent_OnUnload")
                                {
                                    production.ReportDiagnostic(Diagnostic.Create(InvalidAgent, method.Locations.FirstOrDefault(), "Agent entry points are generated; remove conflicting manual exports."));
                                    return;
                                }
            string agent = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string source = """
                // <auto-generated/>
                #nullable enable
                namespace JvmBridge.Generated
                {
                    internal static class NativeAgentExports
                    {
                        [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "Agent_OnLoad")]
                        public static int Load(nint machine, nint options, nint reserved)
                            => global::JvmBridge.Agents.AgentRuntime.Start(static () => new AGENT_TYPE(), machine, options, false);
                        [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "Agent_OnAttach")]
                        public static int Attach(nint machine, nint options, nint reserved)
                            => global::JvmBridge.Agents.AgentRuntime.Start(static () => new AGENT_TYPE(), machine, options, true);
                        [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = "Agent_OnUnload")]
                        public static void Unload(nint machine) => global::JvmBridge.Agents.AgentRuntime.Stop(machine);
                    }
                }
                """;
            production.AddSource("NativeAgentExports.g.cs", SourceText.From(source.Replace("AGENT_TYPE", agent), Encoding.UTF8));
        });
    }

    private static bool DerivesAgent(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? parent = type.BaseType; parent != null; parent = parent.BaseType)
            if (parent.ToDisplayString() == "JvmBridge.Agents.JavaAgent")
                return true;
        return false;
    }

    private static System.Collections.Generic.IEnumerable<INamedTypeSymbol> AllTypes(INamespaceSymbol scope)
    {
        foreach (INamedTypeSymbol type in scope.GetTypeMembers())
        {
            yield return type;
            foreach (INamedTypeSymbol nested in NestedTypes(type))
                yield return nested;
        }
        foreach (INamespaceSymbol child in scope.GetNamespaceMembers())
            foreach (INamedTypeSymbol type in AllTypes(child))
                yield return type;
    }

    private static System.Collections.Generic.IEnumerable<INamedTypeSymbol> NestedTypes(INamedTypeSymbol parent)
    {
        foreach (INamedTypeSymbol type in parent.GetTypeMembers())
        {
            yield return type;
            foreach (INamedTypeSymbol nested in NestedTypes(type))
                yield return nested;
        }
    }
}
