<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
  </PropertyGroup>
  <ItemGroup><AdditionalFiles Include="AnalyzerReleases.Unshipped.md" /><PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" /></ItemGroup>
</Project>
