using System.Net;
using System.Security.Cryptography;
using System.Text.RegularExpressions;

using JvmBridge.Build.Infrastructure;
using JvmBridge.Build.Models;

namespace JvmBridge.Build;

internal sealed class BindingGenerator(RepositoryContext repository, ProcessRunner processRunner)
{
    private readonly RepositoryContext _repository = repository;
    private readonly ProcessRunner _processRunner = processRunner;

    public async Task GenerateAsync(bool check, CancellationToken cancellationToken)
    {
        string provenancePath = _repository.PathFromRoot(parts: ["src", "JvmBridge.Build", "headers", "provenance.json"]);
        HeaderProvenance provenance = JsonFile.Read<HeaderProvenance>(provenancePath);

        foreach ((string name, string expected) in provenance.Headers)
        {
            string headerPath = _repository.PathFromRoot(parts: ["src", "JvmBridge.Build", "headers", name.Replace(oldChar: '/', Path.DirectorySeparatorChar)]);
            byte[] header = await File.ReadAllBytesAsync(headerPath, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            string actual = Convert.ToHexStringLower(SHA256.HashData(header));

            if (!string.Equals(actual, expected, StringComparison.OrdinalIgnoreCase))
                throw new InvalidOperationException($"Header checksum mismatch: {name}");
        }

        using TemporaryDirectory temporary = new(prefix: "jvmbridge-bindings-");

        string temporaryOutput = Path.Combine(temporary.Path, path2: "Bindings.cs");
        List<string> command = [];
        string? clangSharp = Environment.GetEnvironmentVariable(variable: "CLANGSHARP");

        if (clangSharp is not null)
            command.Add(clangSharp);
        else
            command.AddRange(["dotnet", "tool", "run", "ClangSharpPInvokeGenerator", "--"]);

        command.AddRange(
            [
            "-f", "headers/jni.h", "headers/jvmti.h",
            "-I", "shim", "-I", "headers", "-I", "headers/linux",
            "-x", "c", "-a", "--target=aarch64-unknown-linux-gnu",
            "-n", "JvmBridge.Native", "-o", temporaryOutput,
            "-c", "codegen=latest",
            "-g", "helper-types", "file-scoped-namespaces", "macro-bindings", "doc-includes",
            "-e", "Agent_OnLoad", "Agent_OnAttach", "Agent_OnUnload", "JNI_OnLoad", "JNI_OnUnload", "JNI_CreateJavaVM", "JNI_GetCreatedJavaVMs", "JNI_GetDefaultJavaVMInitArgs",
            "-r", "jlong=long", "-wcc", "*=Winapi"
        ]
        );
        await _processRunner.RunCheckedAsync(
            command,
            timeout: TimeSpan.FromMinutes(minutes: 5),
            workingDirectory: _repository.PathFromRoot(parts: ["src", "JvmBridge.Build"]),
            echo: true,
            cancellationToken: cancellationToken
        ).ConfigureAwait(continueOnCapturedContext: false);

        string result = await File.ReadAllTextAsync(temporaryOutput, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        result = VariadicSlotRewriter.Rewrite(result);
        result = Regex.Replace(
            result,
            pattern: "^([ \\t]*)/// <include file='[^']+' path='doc/member\\[@name=\"([^\"]+)\"\\]/\\*' />$",
            static match => $"{GroupValue(match, index: 1)}/// <summary>\n{GroupValue(match, index: 1)}/// Provides the pinned OpenJDK native declaration for <c>{WebUtility.HtmlEncode(GroupValue(match, index: 2))}</c>.\n{GroupValue(match, index: 1)}/// </summary>",
            RegexOptions.Multiline | RegexOptions.CultureInvariant
        );
        result = AddMissingDocumentation(result);
        result = "// <auto-generated/>\n#pragma warning disable CS8981 // Preserve native identifiers.\n// OpenJDK declarations: see NOTICE.md and src/JvmBridge.Build/headers/provenance.json.\n" + result;
        result = TextFile.NormalizeLineEndings(result);

        string outputPath = _repository.PathFromRoot(parts: ["src", "JvmBridge", "Native", "Generated", "Bindings.g.cs"]);

        if (check)
        {
            string existing = File.Exists(outputPath) ? await File.ReadAllTextAsync(outputPath, cancellationToken).ConfigureAwait(continueOnCapturedContext: false) : string.Empty;

            if (!File.Exists(outputPath) || !string.Equals(existing, result, StringComparison.Ordinal))
                throw new InvalidOperationException(message: "Generated bindings are stale. Run `dotnet msbuild build.proj -t:Generate`.");
        }
        else
        {
            TextFile.Write(outputPath, result);
        }

        ConsoleOutput.WriteLine(check ? "Generated bindings verified." : "Generated bindings written.");
    }

    internal static string AddMissingDocumentation(string source)
    {
        List<string> documented = [];

        using StringReader reader = new(source);

        while (reader.ReadLine() is { } line)
        {
            if (line == "public static partial class Methods")
                documented.AddRange(["/// <summary>", "/// Provides constants copied from the pinned OpenJDK headers.", "/// </summary>"]);

            Match constant = Regex.Match(line, pattern: "^(?<indent>[ \\t]*)public const \\S+ (?<name>[A-Za-z_][A-Za-z0-9_]*) = .+;$", RegexOptions.CultureInvariant);

            if (constant.Success)
            {
                string? attribute = null;

                if (documented.Count > 0 && documented.Last().TrimStart().StartsWith(value: "[NativeTypeName(", StringComparison.Ordinal))
                {
                    attribute = documented.Last();
                    documented.RemoveAt(documented.Count - 1);
                }

                string indentation = GroupValue(constant, name: "indent");
                string name = WebUtility.HtmlEncode(GroupValue(constant, name: "name"));
                documented.AddRange(
                    [
                    $"{indentation}/// <summary>",
                    $"{indentation}/// Provides the pinned OpenJDK native constant <c>{name}</c>.",
                    $"{indentation}/// </summary>"
                ]
                );

                if (attribute is not null)
                    documented.Add(attribute);
            }

            Match bitfield = Regex.Match(line, pattern: "^(?<indent>[ \\t]*)public uint (?<name>_bitfield[0-9]+);$", RegexOptions.CultureInvariant);

            if (bitfield.Success)
            {
                string indentation = GroupValue(bitfield, name: "indent");
                string name = WebUtility.HtmlEncode(GroupValue(bitfield, name: "name"));
                documented.AddRange(
                    [
                    $"{indentation}/// <summary>",
                    $"{indentation}/// Stores the packed JVMTI capability flags in <c>{name}</c>.",
                    $"{indentation}/// </summary>"
                ]
                );
            }

            documented.Add(line);
        }

        return string.Join(separator: '\n', documented) + "\n";
    }

    private static string GroupValue(Match match, int index)
    {
        return match.Groups.Cast<Group>().ElementAt(index).Value;
    }

    private static string GroupValue(Match match, string name)
    {
        return match.Groups[name].Value;
    }
}
