using System.Globalization;
using System.Text.Json.Nodes;

using JvmBridge.Build.Infrastructure;
using JvmBridge.Build.Models;

namespace JvmBridge.Build;

internal sealed class CompatibilityReporter(RepositoryContext repository)
{
    private readonly RepositoryContext _repository = repository;

    public void Report(bool verify, bool check)
    {
        CompatibilityConfiguration configuration = JsonFile.Read<CompatibilityConfiguration>(_repository.PathFromRoot(parts: ["src", "JvmBridge.Build", "compatibility.json"]));
        List<JdkEntry> entries = JsonFile.Read<JdkLock>(_repository.PathFromRoot(parts: ["src", "JvmBridge.Build", "jdks.lock.json"])).Jdks;

        HashSet<JvmMatrixCell> expected = [.. entries
            .Where(entry => entry.Status == "available")
            .Select(entry => new JvmMatrixCell(entry.Rid, entry.Java, entry.Implementation))];

        List<JsonObject> results = ReadResults();

        if (verify)
        {
            CoverageValidator.Validate(entries, results);

            foreach (TargetConfiguration target in configuration.Targets.Where(target => target.Agent || target.Build))
            {
                string summaryPath = Path.Combine(_repository.Artifacts, path2: "results", target.Rid, path4: "build-summary.json");
                BuildSummary summary = JsonFile.Read<BuildSummary>(summaryPath);

                if (summary.Rid != target.Rid || summary.Status != "build-verified")
                    throw new InvalidOperationException("Native exports were not verified for " + target.Rid);
            }

            ConsoleOutput.WriteLine($"All {expected.Count} available JVM combinations passed real NativeAOT tests.");

            return;
        }

        using StringWriter text = new(CultureInfo.InvariantCulture);

        text.Write(
            value: "# Compatibility inventory\n\nGenerated by `dotnet build src/JvmBridge.Build -c Release -t:Generate -p:RestoreLockedMode=true` from pinned vendor inventories. Availability is not a claim that tests passed. See the matching commit’s CI reports for runtime verification.\n\n"
        );
        text.Write(
            value: "Each available Java/implementation/target combination is required by CI. Versions with no matching vendor archive are accounted for in the lock file.\n\n| Native target | HotSpot majors available | OpenJ9 majors available | Status / limitation |\n|---|---|---|---|\n"
        );

        foreach (TargetConfiguration target in configuration.Targets)
        {
            List<string> versions = [];

            foreach (string implementation in configuration.Implementations)
            {
                string values = string.Join(
                    separator: ", ",
                    entries
                    .Where(entry => entry.Rid == target.Rid && entry.Implementation == implementation && entry.Status == "available")
                    .Select(entry => entry.Java.ToString(System.Globalization.CultureInfo.InvariantCulture))
                );

                versions.Add(string.IsNullOrEmpty(values) ? "—" : values);
            }

            string state = target.Agent
                ? "Full agent + host + ABI tests required"
                : (target.Build ? "Native build required; " : string.Empty) + Require(target.Status, target.Rid + " status") + ": " + Require(target.Reason, target.Rid + " reason");

            text.Write($"| {target.Rid} | {versions.First()} | {versions.ElementAt(index: 1)} | {state} |\n");
        }

        text.Write(value: "\nJava majors: ");
        text.Write(string.Join(separator: ", ", configuration.JavaMajors));
        text.Write(
            value: ". One pinned GA build per available major/distribution/target; historical patch releases are not exhaustively tested. Android ART is not a Java SE version and needs its own platform suite. Browser/WASI and other non-NativeAOT targets cannot load this agent.\n"
        );

        foreach (VmOptionRule rule in configuration.VmOptionRules)
        {
            text.Write(
                $"\nJava {rule.Java} {rule.Implementation} {rule.Architecture} is exercised with `{string.Join(separator: ' ', rule.Options)}`. {rule.Reason}\n"
            );
        }

        string path = _repository.PathFromRoot(parts: ["docs", "compatibility.md"]);
        string result = text.ToString();

        if (check)
        {
            if (!File.Exists(path) || !string.Equals(File.ReadAllText(path), result, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    message: "Compatibility documentation is stale. Run `dotnet build src/JvmBridge.Build -c Release -t:Generate -p:RestoreLockedMode=true`."
                );
            }
        }
        else
        {
            TextFile.Write(path, result);
        }

        ConsoleOutput.WriteLine($"{expected.Count} available combinations inventoried.");
    }

    private static string Require(string? value, string description)
    {
        return value ?? throw new InvalidOperationException($"Missing {description}.");
    }

    private List<JsonObject> ReadResults()
    {
        List<JsonObject> results = [];
        string root = Path.Combine(_repository.Artifacts, path2: "results");

        if (!Directory.Exists(root))
            return results;

        foreach (string path in Directory.EnumerateFiles(root, searchPattern: "result.json", SearchOption.AllDirectories))
            results.Add(JsonFile.Read<JsonObject>(path));

        return results;
    }
}
